### ISSUE TITLE
using bash to send commands to HMS-52xx

### ISSUE THREAD

**Issue by ExperimentalZeros** [wd5gnr/mhs5200a#5]
This is more of a request for help:

   .... months ago I used the information from your github (and the rest of the internet) to figure a way to send commands from bash to this device: and got it running, no issues... and I am pretty sure I save the instructions in a "safe" place for future usage...  

   But now I cannot find it anywhere.

   I am sure I used **echo** (setting stty for hardware flow) or **picocom**  for the commands to work, but nothing yet.

   Could you please, if possible, provide an example of how one could just send **Commands** over bash?

   Your help is greatly appreciated.

**Comment by ExperimentalZeros** [comment]
I just remembered:

set **stty** as you have on your bash script:

`reset; stty -F /dev/ttyUSB0 57600 cread ignbrk -brkint -icrnl -imaxbel -opost -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke min 60 time 1 -crtscts`

.... and the rest is just send the samples , for example with **echo** just type:

`echo ':r0c' > /dev/ttyUSB0; read X < /dev/ttyUSB0; echo $X` <-- This command will display "Model"

`echo ":s1f6000" > /dev/ttyUSB0 ` <- This command will set the DDS to 60 Hz

Thanks for your work!

**Comment by wd5gnr** [comment]
Sorry I missed your original question. Looks like you figured it out though. Have fun!
